### PR TITLE
Fix exporting cohort name when no filters selected

### PR DESCRIPTION
**Pull request by melissachang**
I noticed that regardless of what's in text field, the exported cohort name is "all participants".

Repro:
- Go to your clinical AMP PD DE. (I already fixed 1000 Genomes, and I'm fixing the other DE's except for clinical.)
- Make sure no filters are selected. Click on Save button. Type anything into text field
- Click Send
- Copy the url param and decode at https://urldecoder.org
- Open new tab with decoded url
- You'll see cohort name is `all_participants`

Fix by making TextField a [React controlled component](https://reactjs.org/docs/forms.html#controlled-components):

```
<TextField
  value={this.state.cohortName}
```

### CODE REVIEW

**Comment by wnojopra** [comment]
Just to be clear, this happens only when no facet values are selected? (If I have some facet values selected, the cohort name is fine?)

**Comment by melissachang** [comment]
Correct

**Comment by wnojopra** [comment]
You're going to have a fix a minor conflict after pulling my latest changes to ExportFab.js. Can you fix that first please?

**Comment by melissachang** [comment]
Done, good point

**Pull request merged**
